# Generated by Django 4.2 on 2023-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('familiya', models.CharField(help_text='Фамилия', max_length=50)),
                ('imya', models.CharField(help_text='Имя', max_length=50)),
                ('phone_number', models.CharField(help_text='Телефон', max_length=12)),
                ('age', models.IntegerField(help_text='Возраст')),
                ('sex', models.CharField(help_text='Пол', max_length=10)),
                ('table', models.CharField(help_text='Бронь стола', max_length=50)),
                ('instagram', models.CharField(max_length=150)),
                ('is_accepted', models.BooleanField(help_text='Допущен')),
                ('is_pay', models.BooleanField(help_text='Оплачен')),
                ('cost', models.IntegerField(help_text='Сумма')),
            ],
            options={
                'verbose_name': 'Заявки на бронь',
            },
        ),
    ]
